ALTER TABLE payment_methods ADD COLUMN required_customer_group_id INT;
ALTER TABLE payment_methods ADD CONSTRAINT fk_paymentmethods_reqcustomergroups FOREIGN KEY (required_customer_group_id) REFERENCES customer_groups;
