#!/usr/bin/env bash

# Daily robots
#
# See README.md for more information.

cd $(dirname $0)
cd ..

./scripts/robot_runner vacuum_analyze
./scripts/robot_runner fulltext_indexer
./scripts/robot_runner import_delivery_service_branches
