#!/usr/bin/env bash

# Regular robots
#
# See README.md for more information.

cd $(dirname $0)
cd ..

./scripts/robot_runner refresh_mv_card_categories_robot.php
./scripts/robot_runner payment_status_checker
