<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>500: Internal Server Error</title>
		<meta name="viewport" content="width=device-width,initial-scale=1.0">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
		<style>
			body {
				font-family: "Liberation Sans", "Nimbus Sans L", Tahoma, Geneva, "Helvetica Neue", Helvetica, Arial, sans-serif;
				margin: 0;
				min-height: 80vh;
				display: flex;
				flex-direction: column;
				justify-content: center;
			}
			h1 {
				font-size: 2.25rem;
				font-weight: 900;
				margin: 30px 0;
				line-height: 1.5;
			}
			h2 {
				font-size: 1.5rem;
				font-weight: 900;
				margin: 30px 0;
				line-height: 1.5;
			}
			p {
				margin: 30px 0;
				color: #666;
				line-height: 1.5;
			}
			hr {
				border: none;
				border-top: 1px solid #ccc;
			}
			.row {
				display: flex;
				align-items: center;
				justify-content: space-between;
			}
			.img-fluid {
				max-width: 100%;
				height: auto;
			}
			.col-text {
				flex-basis: 50%;
				padding: 30px;
			}
			.col-image {
				padding: 0 30px;
				flex-basis: 50%;
				text-align: center;
			}
			.fas, .far {
				color: #666;
				margin-left: 0.25em;
			}
			.fa-exclamation-triangle {
				color: orange;
			}
			@media(max-width: 600px){
				.row {
					display: block;
				}
				.col-text {
					margin-bottom: 30px;
				}
				.col-image {
					padding: 0 60px;
				}
			}
		</style>
		
	</head>
	<body>
		<div class="row">
			<div class="col-text">
				<h1><i class="fas fa-exclamation-triangle"></i> Internal Server Error</h1>
				<p>An internal server error occured.</p>
				<hr>
				<h2><i class="fas fa-wrench"></i> Vnitřní chyba systému</h2>
				<p>Došlo k vnitřní chybě systému. Chyba byla zaznamenána a bude opravena. Opakujte prosím váš požadavek později.</p>
			</div>
			<div class="col-image">
				<img src="/public/dist/images/error_500.jpg" alt="Internal Server Error" class="img-fluid">
			</div>
		</div>
	</body>
</html>
